### PR TITLE
Tidy up README and add subcommand instructions

### PR DESCRIPTION
**Pull request by itsspriyansh**
This PR 
- adds information about available subcommands and dotcommands in `README.md`.
- Adds Information about standalone setup in `README.md`.
- Moves the app and web testing docs to separate files.

### CODE REVIEW

**Comment by garg3133** [comment]
@itsspriyansh We'd need to reduce the README to only the most important information and move all the detailed information to separate pages. Otherwise, someone exploring this project would never reach the part you've implemented through the readme.

See #30 for reference.

**Comment by itsspriyansh** [comment]
@garg3133 PR updated. How does it look now?

**Comment by garg3133** [comment]
@itsspriyansh Not what I meant. What I meant was to move the detailed usage sections of setting up Android/iOS requirements to separate files (as was attempted in #30 but then the author abandoned the PR) so that the README is freed up and only contains the important details.

The amount of information that you added earlier in README related to your work seemed alright, we should have some basic usage about each subcommand in the main readme itself and then move the rest to corresponding files.

**Comment by garg3133** [comment]
What's left now is to link the specific subcommand docs with the appropriate sections in README and update the subcommand files for the recently merged scripts.

**Pull request merged**
